# Generated by Django 3.2.3 on 2021-11-08 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zip_code',
            new_name='zipcode',
        ),
    ]
